version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:3.3.0
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - restore_cache:
          keys:
            - cache-{{ checksum "Gemfile.lock" }}
            - cache-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Run cop and rspec
          command: |
            bundle exec rake

